name: Hello World
on: workflow_dispatch


jobs:
    hello_job:
        runs-on: ubuntu-latest
        steps:
        - name: Echo text
          run: echo "Hello-world!"
    world_job:
        runs-on: ubuntu-latest
        needs: hello_job
        steps:
        - name: display
          timeout-minutes: 1
          run: |
            echo "hi"
            sleep 100s                    